### PR TITLE
change canonical json package

### PR DESCRIPTION
**Pull request by jfrazelle**
wait for https://github.com/endophage/gotuf/pull/41 first

### CODE REVIEW

**Comment by jfrazelle** [comment]
3 steps here:

1. update gotuf
2. update here
3. then I will submit the patch to docker

ping @tiborvass :) who finally saved the day

**Comment by tiborvass** [comment]
@jfrazelle it should be a drop-in replacement for `encoding/json`

**Comment by jfrazelle** [comment]
ya that works here but it wasnt working for the gotuf patch... it was super weird... looking into it

**Comment by tiborvass** [comment]
Also, as an FYI, it doesn't handle Unicode Form C normalization, which is not specified as "required" in the spec-thats-not-a-spec. On the other hand, the package it replaces, also didn't handle it.

**Comment by jfrazelle** [comment]
ah i know how to fix other ;)

**Comment by jfrazelle** [comment]
the last commit here is just a test with the changes to go tuf from my PR there

**Comment by jfrazelle** [comment]
ugh i hate godeps

**Comment by jfrazelle** [comment]
its green boom!

**Comment by jfrazelle** [comment]
either merge this or #192,

**Comment by endophage** [comment]
Need to merge [this](https://github.com/endophage/gotuf/pull/41) before we can merge this PR.

As far as #192, I appreciate the thought but we're not having any meaningful problems with godeps.

**Comment by jfrazelle** [comment]
ok this has been updated

**Comment by jfrazelle** [comment]
we are almost halfway through ;)

**Pull request merged**
