### PR TITLE
Bump go-connections and canonical go dependencies to the latest version

### PR DESCRIPTION
**Pull request by cyli**
Logging bugfix for github.com/docker/go-connections
github.com/docker/go rebased to go 1.6

Especially if 1.6 is needed for https://github.com/docker/notary/issues/591, it might be nice to have canonical go dependency updated

### CODE REVIEW

**Comment by riyazdf** [comment]
This is going to be awesome, thanks for moving the godeps to `vendor`!  We might need to update our checks (vet, fmt, lint, misspell) to point to that directory instead now

**Comment by cyli** [comment]
@riyazdf Thanks for the reminder!  I totally forgot about the Makefile and that explains all the errors :D

**Comment by riyazdf** [comment]
LGTM!

**Comment by endophage** [comment]
LGTM! Standardized vendoring makes me happy :-)

**Pull request merged**
