### PR TITLE
Docs: typo

### PR DESCRIPTION
**Pull request by HuKeping**
Signed-off-by: Hu Keping <hukeping@huawei.com>

### CODE REVIEW

**Comment by cyli** [comment]
@HuKeping Apologies, I added an extra builder in circleci for a test, and I think this has thrown it off a bit.  Can you make a small modification (such as to the commit message) and force-push?

**Comment by cyli** [comment]
@HuKeping Also, thanks for spotting this and fixing!  It LGTM once we can get the CI to pass.

**Comment by HuKeping** [comment]
It's OK, updated @cyli

**Comment by cyli** [comment]
Thanks @HuKeping!  LGTM!

**Pull request merged**
