### PR TITLE
Update vendor spf13

### PR DESCRIPTION
**Pull request by HuKeping**
We can use viper.OnConfigChange() to monitor the change of the config file as the trigger for hot configuration reloading.

Signed-off-by: Hu Keping <hukeping@huawei.com>

### CODE REVIEW

**Comment by cyli** [comment]
jenkins, test this please

**Comment by cyli** [comment]
jenkins, test this please

**Comment by endophage** [comment]
I think we've agreed on just have a method to dial up/down the logging in a running server and otherwise doing a graceful shutdown. Can we close this as we won't be using the file watcher stuff?

**Comment by HuKeping** [comment]
Closing this.

**Pull request closed without merging**
