### PR TITLE
Add the buildtags to go list ./... in the Makefile

### PR DESCRIPTION
**Pull request by cyli**
Also, remove `+build pkcs11 ` build tag from the signer.

Thanks to @endophage for noticing that previously, signer tests weren't be run  :(

### CODE REVIEW

**Comment by endophage** [comment]
LGTM pending CI

**Comment by riyazdf** [comment]
noticing a `go vet` error not related to code in this PR, but being flagged since the tags were updated -- seems that we need to update a lock to use a pointer in `notary-signer/main.go`?

**Comment by cyli** [comment]
@riyazdf Thanks!  Changed to pointer :)

**Comment by riyazdf** [comment]
LGTM.  Codecov is fine here with me too, though the reporting shows a slight decrease for some reason

**Comment by endophage** [comment]
Yep LGTM. The codecov diff already existed, we just couldn't see it because the notary-signer package wasn't being tested.

**Pull request merged**
