### PR TITLE
Add to maintainers list

### PR DESCRIPTION
**Pull request by riyazdf**
Signed-off-by: Riyaz Faizullabhoy <riyaz.faizullabhoy@docker.com>

### CODE REVIEW

**Comment by cyli** [comment]
LGTM!

**Comment by thaJeztah** [comment]
ping me after this is merged, then I can add @riyazdf to the maintainers mailinglist as well :+1:

**Comment by endophage** [comment]
LGTM 

@thaJeztah merging right now

**Comment by thaJeztah** [comment]
Invitation sent!

**Comment by riyazdf** [comment]
@thaJeztah got it, thanks!

**Pull request merged**
