### PR TITLE
adding logo

### PR DESCRIPTION
**Pull request by endophage**
The docker design team requested that they do the Logo before the project lands in CNCF. This PR should be considered the vote. I will be responsible for merging assuming this passes  the two-thirds vote.

+1 from me.

Signed-off-by: David Lawrence <david.lawrence@docker.com> (github: endophage)

### CODE REVIEW

**Comment by endophage** [comment]
Maintainers for sign-off:

@ecordell @HuKeping @riyazdf @cyli @NathanMcCauley @diogomonica

**Comment by thaJeztah** [comment]
Is there a different license and/or copyright for the Logo (just double checking, I recall there being a discussion for containerd)

**Comment by endophage** [comment]
@thaJeztah The logo was created specifically because we were doing the donation and is intended to transfer with the repo as far as I know.

**Comment by HuKeping** [comment]
+1 from me.

**Comment by NathanMcCauley** [comment]
LGTM

**Comment by diogomonica** [comment]
LGTM

**Pull request merged**
