### PR TITLE
Fix a wrong function call

### PR DESCRIPTION
**Pull request by HuKeping**
Signed-off-by: Hu Keping <hukeping@huawei.com>

### CODE REVIEW

**Comment by endophage** [comment]
Oh man, that was probably me. 

Why did it work? It worked because All TUF files share a certain amount of high level structure so even though we were unmarshalling into the wrong struct, it still parsed `snapshot.Signed.Version` into the expected field, and we were retrieving the correct raw JSON from cache.

Thank you!

LGTM!

**Comment by riyazdf** [comment]
good find, LGTM!

**Comment by cyli** [comment]
Nice catch!  LGTM!

**Comment by HuKeping** [comment]
>  It worked because All TUF files share a certain amount of high level structure 

Yes it is, and I also noticed that the `[Targets/Timestamp/Snapshort]FromSigned` are almost the same, does it worth to create a common function?

**Pull request merged**
