### PR TITLE
Bump gRPC to v1.0.1-GA

### LINKED ISSUE #930: Update to gRPC 1.0
Not sure what exactly is required here but probably need to:

- make sure we install the correct version if any of the containers are installing and building the protobufs
- update the vendored dependencies
- rebuild the protobufs committed into the repo.

https://cloudplatform.googleblog.com/2016/08/gRPC-a-true-Internet-scale-RPC-framework-is-now-1-and-ready-for-production-deployments.html

### PR DESCRIPTION
**Pull request by HuKeping**
Closes #930 

This is the first GA (General Availability) release of gRPC-go.

Have Rebuilded the protobufs and nothing change.

Signed-off-by: Hu Keping <hukeping@huawei.com>

### CODE REVIEW

**Comment by cyli** [comment]
jenkins, test this please

**Comment by cyli** [comment]
Thank you for bumping this dependency @HuKeping!  LGTM pending CI.

**Comment by riyazdf** [comment]
thank you @HuKeping, LGTM!

We'll need to drop the `documentation` hook since that was effectively de-commissioned by https://github.com/docker/notary/pull/929 and make sure the yubikey jenkins tests show up properly, but those tests are green nonetheless.

**Comment by cyli** [comment]
That job has been disabled I think, so I'm not sure why it marked the status.  I've also disabled updating the status for that job.  Hopefully the next PR won't do that - looks like the yubikey tests have passed, so merging despite the doc issue.

**Pull request merged**
