### PR TITLE
Update version and changelog for 0.4

### PR DESCRIPTION
**Pull request by riyazdf**
Updated `NOTARY_VERSION` and the changelog - I did my best to sift through our milestone and issues/PRs to capture the changes.  The link for the tag on our changelist won't resolve until the tag is published

### CODE REVIEW

**Comment by cyli** [comment]
Should we also add the bit about changing the import export format from zip to PEM?

**Comment by riyazdf** [comment]
@cyli: definitely.  Done 👍

**Comment by HuKeping** [comment]
Are we ready for 0.4 now? I see there's still some issue under 0.4 milestone hasn't been closed yet.

**Comment by riyazdf** [comment]
Hi @HuKeping - thanks for checking in!  This PR isn't officially releasing 0.4, since we'd be merging into the release candidate branch `release/0.4`.  Once v0.4.0 is ready, we'll release the tag to master.

As for the remaining 0.4 issues - https://github.com/docker/notary/issues/735 has a PR open and https://github.com/docker/notary/issues/731 is half-complete (`--rootkey` flag) and the other half in a PR in progress.  We'd like to get both in to a `v0.4.X` but they may not be critical for an initial RC or `v0.4.0`.

**Comment by HuKeping** [comment]
Hi @riyazdf does it make sense also add the relative PR link at the end of each line?

**Comment by riyazdf** [comment]
@HuKeping - definitely would be more than happy to!

**Pull request merged**
