### PR TITLE
Do not lowercase role names when adding a change

### LINKED ISSUE #444: ToLower on path prefix?
https://github.com/docker/notary/pull/371/files#diff-1cd41a2611da49ce63630d5a51bd82c5R271 calls `ToLower` on a role name.

AFAICS the delegation role names are path prefixes, which are typically case-sensitive (UNIX, URLs), so the `ToLower` call seems to be losing information.

What is the intent here? AFAICS the canonical role names are expected to be case-insensitive, but the delegated roles are case sensitive (looking at `data.CanonicalRole`, `utils.FindRoleIndex`, uses of `filepath.Dir`.

### PR DESCRIPTION
**Pull request by cyli**
Signed-off-by: Ying Li <ying.li@docker.com>

Fixes #444

### CODE REVIEW

**Comment by diogomonica** [comment]
LGTM

**Comment by mtrmac** [comment]
:+1:, thanks!

**Comment by diogomonica** [comment]
Is it worth it to add some testing around this?

**Comment by cyli** [comment]
@diogomonica Good point, thanks, will add

**Comment by cyli** [comment]
@diogomonica https://github.com/docker/notary/pull/479/files#diff-fce84029d346504e44323c30d21a3808R809

**Comment by diogomonica** [comment]
LGTM

**Comment by riyazdf** [comment]
LGTM after ci!

**Pull request merged**
