### PR TITLE
change url from jfrazelle/go to docker/go

### PR DESCRIPTION
**Pull request by jfrazelle**

### CODE REVIEW

**Comment by jfrazelle** [comment]
then if you could be so kind as to provide a tagged version (doesnt need to be wrt to the release) that would be great so I can bump in docker/docker#19693

**Comment by riyazdf** [comment]
LGTM pending CI!

**Comment by riyazdf** [comment]
cc @cyli: do we need a rebase/push for yubikey tests to be happy?

**Comment by tiborvass** [comment]
For the record, I think we shouldn't have a `docker/go` repo, but instead a `docker/json` or `docker/canonicaljson` repo. It doesn't have to be addressed in this PR, but just wanted to voice my opinion :)

**Comment by jfrazelle** [comment]
Oh we can name it whatever just so I don't own it ;)

**Comment by jfrazelle** [comment]
I actually don't have perms to change the name now Hahahaha

**Comment by cyli** [comment]
@riyazdf yes, that would make it happy, but I'm fine merging this as is.  LGTM!

**Comment by jfrazelle** [comment]
I rebased :) I like green ;)

**Comment by jfrazelle** [comment]
no bueno :(

**Comment by cyli** [comment]
@jfrazelle All green!  :)

**Comment by jfrazelle** [comment]
thanks!

**Comment by cyli** [comment]
@jfrazelle tag is `docker-v1.10-4` - running some tests now :)

**Comment by jfrazelle** [comment]
thanks so much!

**Comment by jfrazelle** [comment]
granted this probably wont be in the release (fyi) but should be fine ;)

**Comment by cyli** [comment]
@jfrazelle oh oops!  should I tag it something else?  `docker-v1.11-1` maybe?

**Comment by jfrazelle** [comment]
i think its fine :)

**Comment by cyli** [comment]
@jfrazelle Some of the messaging/fallback behavior has changed, so the tests probably need updating to vendor.

**Comment by jfrazelle** [comment]
ah ok i will keep an eye out for failures, thanks for the heads up

**Comment by jfrazelle** [comment]
so yeahhhhh not really sure what to do here haha
do you all mind doing the bump in docker or do you want to send my branch a PR for the tests, heres the output
```
20:26:09 ----------------------------------------------------------------------
20:26:09 FAIL: docker_cli_create_test.go:303: DockerTrustSuite.TestUntrustedCreate
20:26:09 
20:26:09 docker_cli_create_test.go:314:
20:26:09     c.Assert(err, check.Not(check.IsNil))
20:26:09 ... value = nil
20:26:09 
20:26:10 
20:26:10 ----------------------------------------------------------------------
20:26:10 FAIL: docker_cli_pull_trusted_test.go:49: DockerTrustSuite.TestUntrustedPull
20:26:10 
20:26:10 docker_cli_pull_trusted_test.go:61:
20:26:10     c.Assert(err, check.NotNil, check.Commentf(out))
20:26:10 ... value = nil
20:26:10 ... time="2016-01-26T20:26:10Z" level=warning msg="Error while downloading remote metadata, using cached timestamp - this might not be the latest version available remotely" 
20:26:10 Pull (1 of 1): 127.0.0.1:5000/dockercli/trusted:latest@sha256:7638dc75fb6d456b00512a63073ab49e68f8033a8236061bf44bd4641cbd21a8
20:26:10 sha256:7638dc75fb6d456b00512a63073ab49e68f8033a8236061bf44bd4641cbd21a8: Pulling from dockercli/trusted
20:26:10 Digest: sha256:7638dc75fb6d456b00512a63073ab49e68f8033a8236061bf44bd4641cbd21a8
20:26:10 Status: Image is up to date for 127.0.0.1:5000/dockercli/trusted@sha256:7638dc75fb6d456b00512a63073ab49e68f8033a8236061bf44bd4641cbd21a8
20:26:10 Tagging 127.0.0.1:5000/dockercli/trusted@sha256:7638dc75fb6d456b00512a63073ab49e68f8033a8236061bf44bd4641cbd21a8 as 127.0.0.1:5000/dockercli/trusted:latest
20:26:10 
20:26:10 
20:26:11 
20:26:11 ----------------------------------------------------------------------
20:26:11 FAIL: docker_cli_run_test.go:3179: DockerTrustSuite.TestUntrustedRun
20:26:11 
20:26:11 docker_cli_run_test.go:3193:
20:26:11     c.Fatalf("Error expected when running trusted run with:\n%s", out)
20:26:11 ... Error: Error expected when running trusted run with:
20:26:11 time="2016-01-26T20:26:11Z" level=warning msg="Error while downloading remote metadata, using cached timestamp - this might not be the latest version available remotely" 
```

**Comment by cyli** [comment]
@jfrazelle Sure!  The problem is that a bunch of the tests use the same repo, so the tuf metadata is cached.  I was just going to go through and change the repo names so they're all different, or do a cleanup after every test.

**Pull request merged**
