### PR TITLE
replace godeps w bash for better control

### PR DESCRIPTION
**Pull request by jfrazelle**
you are welcome

```
$ git diff --shortstat  HEAD~1
 895 files changed, 325 insertions(+), 76322 deletions(-)
```

### CODE REVIEW

**Comment by jfrazelle** [comment]
how do i change gopath on circle

**Comment by jfrazelle** [comment]
eff circle, it passes locally, i even changed the config

**Comment by jfrazelle** [comment]
flip

take it or leave it im over it

**Comment by endophage** [comment]
@NathanMcCauley @diogomonica @dmcgowan Thoughts? My opinion is godeps has largely been working well for us.

**Comment by jfrazelle** [comment]
but look at the minussss

**Comment by jfrazelle** [comment]
i dont care either way just kinda gross having all the docker src in your
git branch too

**Comment by endophage** [comment]
Mentioned it to @jfrazelle, thought about this a lot last night and the only thing that I really need/want is an equivalent of `godep update github.com/...` otherwise when I'm working on gotuf it's a pain to keep updating the dependencies so I can `docker-compose build`.

I think she's having a think about how to add that functionality.

**Comment by jfrazelle** [comment]
so if gotuf switched to github.com/mattn/go-sqlite3  instead of  code.google.com/p/gosqlite we could get rid of another dep

**Comment by diogomonica** [comment]
I don't usually like witch hunts, but this one is pretty great.

**Comment by endophage** [comment]
@jfrazelle if the mattn one is the same one docker/docker uses I know there was some kind of issue with it. Possibly docker is using an older version that wasn't database/sql compatible?

**Comment by jfrazelle** [comment]
yes it is

**Comment by jfrazelle** [comment]
nah see https://github.com/docker/docker/pull/16054

**Comment by endophage** [comment]
Cool, I'm happy to use that one instead. <3 database/sql interface

**Comment by jfrazelle** [comment]
omg i won

**Comment by jfrazelle** [comment]
the circle ci war

**Comment by jfrazelle** [comment]
JESS: 1, CIRCLECI: 0

**Comment by jfrazelle** [comment]
now that i finally got this to work, i think we should maybe try this 0:) https://github.com/FiloSottile/gvt

**Comment by jfrazelle** [comment]
like a combo so there is still a lot of minus, but it compiles with the vendoring experiment as well

**Pull request closed without merging**
