### PR TITLE
Use a .-relative bind-mounted volume in notarymysql compose section.

### PR DESCRIPTION
**Pull request by cyli**
See https://github.com/docker/notary/pull/359#discussion_r47570016

Signed-off-by: Ying Li <ying.li@docker.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
thanks! lgtm (not a maintainer here)

**Comment by diogomonica** [comment]
The idea was to use a named volume originally, but local bind might be easier to do development on, and still makes sure data isn't lost between invocations. LGTM

**Comment by thaJeztah** [comment]
If a named volume was the intent, then I think the original PR is good (and avoids possible "permissions" issues when using boot2docker). Up to you :smile:

**Comment by diogomonica** [comment]
using `./notarymysql:/var/lib/mysql` doesn't work for me locally.

**Comment by thaJeztah** [comment]
because of permissions probably? In that case, it's probably best to close this PR, and use a named volume as in the original PR. Sorry for the confusion, I thought the intent was using a bind-mounted volume

**Comment by cyli** [comment]
@thaJeztah Same.  Thanks for testing @diogomonica - happy just to go with named volume then.

**Pull request closed without merging**
