### PR TITLE
seems a duplicate 'use'

### PR DESCRIPTION
**Pull request by jzwlqx**

### CODE REVIEW

**Comment by HuKeping** [comment]
Nice catch!

**Comment by riyazdf** [comment]
jenkins, test this please

**Comment by riyazdf** [comment]
LGTM, thank you @jzwlqx for catching and fixing this 👍

**Comment by cyli** [comment]
LGTM!  Thank you @jzwlqx 

Looks like codecov is having issues - this is a pure doc change, so it shouldn't matter, so merging.

**Pull request merged**
