### PR TITLE
Docs: update readme

### PR DESCRIPTION
**Pull request by HuKeping**
Two main things:
- Update the content
- Update broken links

Signed-off-by: Hu Keping <hukeping@huawei.com>

### CODE REVIEW

**Comment by mtrmac** [comment]
:+1:

**Comment by thaJeztah** [comment]
LGTM, thx @HuKeping

**Comment by NathanMcCauley** [comment]
LGTM

**Comment by HuKeping** [comment]
ping...

**Comment by thaJeztah** [comment]
@NathanMcCauley can you merge this one if you accept my LGTM, I don't have permissions in this repository to do so :smile:

**Pull request merged**
