### PR TITLE
added exit on passphrase retrieval in command line by revendoring the…

### PR DESCRIPTION
**Pull request by avaid96**
… term package from docker/docker

Signed-off-by: Avi Vaid <avaid1996@gmail.com>

### CODE REVIEW

**Comment by avaid96** [comment]
jenkins, test this please

**Comment by riyazdf** [comment]
jenkins, test this please.

**Comment by riyazdf** [comment]
jenkins, ok to test

**Comment by cyli** [comment]
Awesome, CTRL-C now cancels out of password prompt.  Thank you for fixing this @avaid96!  LGTM pending CI.

**Comment by riyazdf** [comment]
thanks for updating this, just gave this a spin and LGTM!

**Comment by avaid96** [comment]
awesome! opening new terminals every time was really frustrating me, happy to have this!

**Pull request merged**
