### PR TITLE
convert docker compose files to v2

### PR DESCRIPTION
**Pull request by andrewhsu**
Converted the remaining two docker compose files over to the v2 format as suggested in #753 in hopes that the dns server in docker would resolve the hostnames of the containers instead of going off-box for hostname resolution.

Signed-off-by: Andrew Hsu <andrewhsu@acm.org>

### CODE REVIEW

**Comment by andrewhsu** [comment]
Hmm..looks like the [circleci test failed](https://circleci.com/gh/docker/notary/2991) because it does not have high enough docker version:
```
ERROR: The Docker Engine version is less than the minimum required by Compose. Your current project requires a Docker Engine of version 1.10.0 or greater.
```

**Comment by cyli** [comment]
@andrewhsu Thank you for your contribution!  I'm trying to update our circle config to bump up the docker version:  #756, but am still working out a few kinks

**Comment by endophage** [comment]
We've merged 756 so please rebase and see if CircleCI works now.

**Comment by andrewhsu** [comment]
@endophage i've rebased, but it looks like circleci build failed again. look like https://gopkg.in is down which is preventing go from getting what it needs: https://circleci.com/gh/docker/notary/3040

**Comment by cyli** [comment]
jenkins, test this please

**Comment by cyli** [comment]
@andrewhsu Thank you so much for your contribution!  Apologies for the delayed response - our team has been mostly out of office at conferences and whatnot.    Thank you for splitting the signer out so clients don't have to have access to the signer or DB as well.  

The one non-blocking nitpick I have is that "rdb" in the `docker-compose.rethink.yml` file stands for rethink-db, so would it make sense to change the network in these two to "mysql" or some such?

**Comment by andrewhsu** [comment]
@cyli i've renamed `rdb` to `mdb` instead of `mysql` so that the network name is different from the service name in the docker-compose syntax.

**Comment by riyazdf** [comment]
jenkins, test this please

**Comment by riyazdf** [comment]
thank you for this contribution!  Tested the `docker-compose.yml` locally (the other is covered by `make integration` in CI), LGTM

**Comment by endophage** [comment]
LGTM

**Pull request merged**
