### PR TITLE
fix entropy issues

### PR DESCRIPTION
**Pull request by jfrazelle**
ping @diogomonica @NathanMcCauley :innocent: 

Signed-off-by: Jessica Frazelle <acidburn@docker.com>

### CODE REVIEW

**Comment by tiborvass** [comment]
looks legit to me

**Comment by jfrazelle** [comment]
thank god the tests failed amirite

**Comment by calavera** [comment]
+1

**Comment by diogomonica** [comment]
This PR is intentionally harmful. Closing it.

**Pull request closed without merging**
