### PR TITLE
Set the default output for all cobra commands to be STDOUT

### PR DESCRIPTION
**Pull request by cyli**
Signed-off-by: Ying Li <ying.li@docker.com>

### CODE REVIEW

**Comment by diogomonica** [comment]
Shouldn't we update our tests to make sure we're taking output from STDOUT? How did the tests worked in the first place?

**Comment by cyli** [comment]
@diogomonica In order to read the input, we set the output of the command to be a buffer.  So the tests don't actually test whether the real command is stdout or stderr

**Comment by diogomonica** [comment]
Got it. LGTM

**Comment by endophage** [comment]
LGTM

**Pull request merged**
