### PR TITLE
update maintainers file for parsing

### PR DESCRIPTION
**Pull request by jfrazelle**
update standard for dockerfiles so we can clean up dockers and parse
into one repo

see https://github.com/docker/opensource/pull/35

https://github.com/docker/docker/pull/18321

Signed-off-by: Jessica Frazelle <acidburn@docker.com>

### CODE REVIEW

**Comment by jfrazelle** [comment]
it works https://github.com/docker/opensource/pull/35/files#diff-bb5907b965b501e1856ccd79d2c4f642R34

**Comment by jfrazelle** [comment]
this was just a test y'all can update yoself now

**Comment by jfrazelle** [comment]
reopening to save you all the trouble and @thajeztah is working on PRs to the other subcomponents

**Comment by cyli** [comment]
@jfrazelle Thanks lots for updating this for us!  LGTM, although it looks like it could use a rebase.

**Comment by thaJeztah** [comment]
Oh, that's the GitHub thingy because of protected branches :disappointed:

**Comment by jfrazelle** [comment]
the button is green for me?

**Comment by thaJeztah** [comment]
@jfrazelle you're "owner" so you're allowed to merge even if it's "out of date"

**Comment by jfrazelle** [comment]
oh :innocent:

**Comment by jfrazelle** [comment]
ok i fixed the setting

**Comment by thaJeztah** [comment]
LGTM (but not a maintainer here)

**Comment by cyli** [comment]
@jfrazelle Out of curiosity, what is `docker/is-mergable`?

**Comment by jfrazelle** [comment]
oh i have no idea sorry but looks cool

**Comment by jfrazelle** [comment]
other projects have started merginig these *cough cough*

**Comment by jfrazelle** [comment]
thanks hehehe guilt trip was strong :innocent:

**Comment by cyli** [comment]
:D

**Comment by jfrazelle** [comment]
also check it outtttt
https://github.com/docker/opensource/blob/add-maintainers-file-parsing/MAINTAINERS#L244

**Comment by cyli** [comment]
nice!

**Pull request merged**
