### PR TITLE
add a simple test script, eventually this can grow to be our CI script

### PR DESCRIPTION
**Pull request by NathanMcCauley**
@diogomonica 

Signed-off-by: Nathan McCauley <nathan.mccauley@docker.com>

### CODE REVIEW

**Comment by diogomonica** [comment]
depends on #142 for configurable baseDir (can't just go around and rm -rf trusted directories)

**Comment by diogomonica** [comment]
@NathanMcCauley new version with env passphrases. Now the script takes 1 argument: the server we want to test with.

**Comment by diogomonica** [comment]
@NathanMcCauley ping, is this good enough to be mergeable?

**Comment by NathanMcCauley** [comment]
@diogomonica could you rebase off of master? I can't run it b/c of the version stuff

**Comment by diogomonica** [comment]
@NathanMcCauley this is rebased

**Comment by jfrazelle** [comment]
do u want this to be run on our infra

**Comment by diogomonica** [comment]
@jfrazelle it would be awesome. Not sure if the current format is good for that. Would we just check the return code of the script?

**Comment by jfrazelle** [comment]
all i would need would be a docker build & docker run command, you all hande the rest ;)

**Comment by endophage** [comment]
@diogomonica would love to get this merged. Can you take a look at the changes in cmd/notary and make sure it's all good.

LGTM.

**Pull request merged**
