### PR TITLE
Edited tuf/README

### PR DESCRIPTION
**Pull request by avaid96**
As discussed earlier

### CODE REVIEW

**Comment by riyazdf** [comment]
jenkins, test this please

**Comment by riyazdf** [comment]
LGTM pending CI, thanks for cleaning this up!

**Comment by cyli** [comment]
There seems to be a merge commit as the last commit, and the signing bot is unhappy because merge commits aren't signed.  :)

I think you can probably drop the merge commit, and just sign your first commit, and the bot will be satisfied.

**Comment by riyazdf** [comment]
jenkins, test this please.

**Comment by cyli** [comment]
Thank you @avaid96!  LGTM!

**Pull request merged**
