### PR TITLE
fix formatting in fixture config json files

### PR DESCRIPTION
**Pull request by grantleehoffman**
Changed spaces to tabs in config files specified in Issue #1013

### CODE REVIEW

**Comment by riyazdf** [comment]
jenkins, test this please

**Comment by endophage** [comment]
Gordon is complaining because I did a branch update through GH and the merge commit isn't signed. If CI passes, go ahead and merge.

**Comment by cyli** [comment]
jenkins, test this please

**Comment by grantleehoffman** [comment]
Yep, I noticed that the previous commit wasn't signed. Thanks 👍

**Comment by HuKeping** [comment]
Thanks @grantleehoffman !

**Pull request merged**
