### PR TITLE
Enhance expiry function

### PR DESCRIPTION
**Pull request by HuKeping**
Signed-off-by: Hu Keping <hukeping@huawei.com>

### CODE REVIEW

**Comment by endophage** [comment]
Just to confirm I'm understanding the change correctly. This will cause certs to be identified as expired 10 seconds early?

**Comment by HuKeping** [comment]
Yes @endophage , actually I'm not very certain about whether the check for TUF files needs this buffer-time or not. It's just what we do on almost our Token verification things.

Feel free to close this if it was not a good idea.

**Comment by endophage** [comment]
If you want to take it in another direction: I don't think this is necessary when checking expiry but for server signed timestamps and snapshots, it would be good to build in a buffer time at which a new one gets produced even though the current one has not expired.

**Comment by diogomonica** [comment]
Agreed with @endophage. As is, this PR isn't very useful. Closing for now.

**Comment by HuKeping** [comment]
Agree with @endophage

**Pull request closed without merging**
