### PR TITLE
Update expiry of fixture certs to at least 2 years in the future

### PR DESCRIPTION
**Pull request by cyli**
Signed-off-by: Ying Li <ying.li@docker.com>

### CODE REVIEW

**Comment by riyazdf** [comment]
LGTM on green!

**Comment by cyli** [comment]
Updated this to do another 3 things:

1. use a sha256 signing algorithm instead of whatever is default (which may be SHA1 on older versions of openssl, which we reject)
1. use a different CN for the intermediate cert so we can more easily tell what signed what
1. also generate 2 other certs that are in the fixtures library

**Comment by riyazdf** [comment]
thanks for the updates!  LGTM pending CI :)

**Comment by endophage** [comment]
LGTM

**Pull request merged**
