### PR TITLE
Update vendoring and import for sirupsen/logrus

### PR DESCRIPTION
**Pull request by vdemeester**
Migrate to `github.com/sirupsen/logrus` 👼

- [x] What to do about rethinkdb (i.e. have a "fix branch" for now and update to a recent, rethinkdb fixed version or update it right away) ?

Takes over @simonfrequel PR #1203

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by shouze** [comment]
Ok, so related to #465

**Comment by endophage** [comment]
@vdemeester for gorethink the project is basically dead, the maintainer has said they're not going to do any work on it. We should create a fork under docker or moby that has just the sirupsen logging fix. It's going to be needed for docker's enterprise products too. I believe `vndr` supports cloning a repo, i.e. github.com/docker/gorethink, in to an alternative namespace, i.e. github.com/dancannon/gorethink

**Comment by shouze** [comment]
@endophage @vdemeester ok good news, so who can create this github.com/docker/gorethink fork?

The actual PR already points to a fork https://github.com/docker/notary/pull/1211/files#diff-4061fcef378a6d912e14e2ce162a1995R50

**Comment by vdemeester** [comment]
@endophage I'll prepare a fork tomorrow 👼

**Comment by endophage** [comment]
@shouze We should put a fork under the docker org for long term stability/reliability/availability but otherwise I think we'd be happy to merge this.

**Pull request closed without merging**
