### PR TITLE
Adding version to notary

### PR DESCRIPTION
**Pull request by diogomonica**
@jfrazelle, what vars do you want me to have in main.go for the -X on the makefile?

Signed-off-by: Diogo Monica <diogo@docker.com>

### CODE REVIEW

**Comment by jfrazelle** [comment]
can you do a seperate package like https://github.com/docker/docker/blob/8ffdf6022e88e19c6d1f434a69ff5cbd3dc7db6b/dockerversion/dockerversion.go

**Comment by jfrazelle** [comment]
and just 
```
GITCOMMIT string
	VERSION   string
```

**Comment by jfrazelle** [comment]
why u closeeee

**Comment by diogomonica** [comment]
misclick

**Pull request merged**
