### PR TITLE
compile the notary server binary statically 

### PR DESCRIPTION
**Pull request by jfrazelle**
compile the notary server binary statically in the notary server image so that it can then be copied from the container into a scratch docker image

ping @aaronlehmann then you can use `FROM scratch`

Signed-off-by: Jessica Frazelle <acidburn@docker.com>

### CODE REVIEW

**Comment by jfrazelle** [comment]
also added the ldflags to the one built in the signer dockerfile so that binary has them as well

**Comment by jfrazelle** [comment]
didnt statically compile that one tho because its probably hopeless and will need `softhsm2` in the image anyways, can try tho..

**Comment by aaronlehmann** [comment]
So that's what I tried to do with the registry at first, but it didn't work out because of the cgo use. Same issue with notary-signer. For notary-server I think it's theoretically possible, but I'm not sure it's worth making the notary-server container way different from notary-signer. Also, there may be weird issues that come up running in a "scratch" container, for example if something tries to shell out. And if we ever add a dependency that uses cgo, we'd have to redo the container.

What do you think?

Thanks for the other feedback as well. I'll act on it tomorrow.

**Comment by jfrazelle** [comment]
what would you shell out to? but ya i see your point i will just add the ldflags

**Comment by jfrazelle** [comment]
updated, im a big fan of static binaries tho bc i hate installing things haha

**Comment by aaronlehmann** [comment]
I'll defer to others on this, but it seems a little weird to me to end up with notary-server being static and notary-signer being dynamic. I'd like them to be as consistent as possible. And I don't think there's much advantage to notary-server having a tiny container if it would otherwise use the same base layer as notary-signer.

**Comment by jfrazelle** [comment]
i changed to both dynmic

**Comment by jfrazelle** [comment]
just didnt change the PR title or branch name

**Comment by aaronlehmann** [comment]
Oh, okay, I didn't actually look at the diff. Could you please squash the commits and change the commit message to reflect what's being done, and then I'll merge. Thanks!

**Comment by jfrazelle** [comment]
will do!

**Comment by jfrazelle** [comment]
done

**Comment by jfrazelle** [comment]
Btw you already merged https://github.com/docker/notary/pull/168 and it doesn't work without this patch. Which I said....

**Comment by jfrazelle** [comment]
MERGE MY PR
...

i'll wait...
waiting

**Comment by aaronlehmann** [comment]
LGTM

**Comment by NathanMcCauley** [comment]
LGTM

**Pull request merged**
