### PR TITLE
Minor improvements on server url

### PR DESCRIPTION
**Pull request by ggtools**
- Add the `--server` parameter for `verify``
- Add and environment variable to specify the default server URL

### CODE REVIEW

**Comment by NathanMcCauley** [comment]
LGTM

**Comment by thaJeztah** [comment]
should the environment variable be documented somewhere?

**Comment by diogomonica** [comment]
LGTM

@thaJeztah can you please confirm the right location for these docs? The more I look at this, the less I want the same structure as docker/docker, where I can't find anything in :(

**Comment by thaJeztah** [comment]
Well, I think it needs to be documented *somewhere*, but I'm not sure the current amount of docs here needs a whole page.

ping @moxiegirl any thoughts here? You've been doing a lot of research into the docs/navigation structure.

**Comment by diogomonica** [comment]
@moxiegirl in particular, any chance we can do a simpler version of the docs for notary, instead of the docker style?

Maybe something like this? http://lyndaoleary.github.io/docker-api-docs/#list-containers

**Comment by moxiegirl** [comment]
@diogomonica By "docker look" You mean the theme? Yes, I'm working on that right now. I have a redesign from Josephine on the UX team. It is similar to the Readme.io look that seems to be rising in fashion.  I'm about to close on a contract with a scripting team to implement this shortly.

@diogomonica I'd prefer we talk in person about your concern's with the docs structure.  @thaJeztah isn't really responsible for that..

**Comment by ggtools** [comment]
@thaJeztah I agree that, at the moment, having of whole page for an environment variable is way overkill. However in the current documentation state I didn't find a *natural* place to put it. Beside, it does not seem totally awkward to have, in the future, a page dedicated to the cli usage.

**Comment by moxiegirl** [comment]
LGTM on current format. If we need to move bits around we can do that before the release.

**Pull request merged**
