### PR TITLE
Add ecordell as a maintainer

### PR DESCRIPTION
**Pull request by ecordell**
🎉

### CODE REVIEW

**Comment by riyazdf** [comment]
jenkins, test this please

**Comment by cyli** [comment]
LGTM!  Welcome @ecordell!  :D

**Comment by cyli** [comment]
jenkins, test this please

(although that seems really unnecessary :P)

**Comment by endophage** [comment]
FYI, due to the GH permissions model I can't add people from outside the docker org to teams, I've pinged somebody with permissions to do that and if memory serves you'll get an email when they do. Sorry for the delay!

**Comment by ecordell** [comment]
No worries!

**Comment by diogomonica** [comment]
LGTM! Welcome @ecordell

**Pull request merged**
