### PR TITLE
Move all imports of sqlite3 to tests only

### PR DESCRIPTION
**Pull request by cyli**
Signed-off-by: Ying Li <ying.li@docker.com>

### CODE REVIEW

**Comment by endophage** [comment]
LGTM!

**Comment by riyazdf** [comment]
LGTM

**Comment by endophage** [comment]
Are there any docs updates that need to be made in relation to not supporting sqlite?

**Comment by cyli** [comment]
@endophage I don't think we said in the docs that we supported sqlite3 at all, just MySQL or an in-memory store.

**Comment by endophage** [comment]
:+1: 

merging then

**Pull request merged**
