### PR TITLE
fixes #1097

### LINKED ISSUE #1097: "nil pointer" error when notary-server is configured with an "auth section"
Hi, 
I pulled latest code and  could successfully setup notary using the default docker compose template.

However when I added "auth section" to server-config.json, like this:
```
"auth": {
        "type": "token",
        "options": {
            "realm": "https://10.117.4.142/service/token",
            "service": "notary-server",
            "issuer": "registry-token-issuer",
            "rootcertbundle": "/go/src/github.com/docker/notary/fixtures/token_root.crt"
        }
    }
```
In which case the url "https://10.117.4.142/service/token" points to a jwt token service I wrote.
I tried to execute notary list and got error:
```
# notary -D -s https://10.117.4.142:4443 list 10.117.4.142/notary-test-4/hello-world:1.0
DEBU[0000] Configuration file not found, using defaults
DEBU[0000] Using the following trust directory: /root/.notary
ERRO[0001] could not reach https://10.117.4.142:4443: Get https://10.117.4.142:4443/v2/: EOF
INFO[0001] continuing in offline mode
DEBU[0001] No yubikey found, using alternative key storage: no library found

* fatal: client is offline
```
Checked the output of notary server container via docker-compose, the error looks like this:
```
server_1  | {"level":"info","msg":"Version: 0.5.0, Git commit: 905fffb","time":"2017-02-14T08:33:30Z"}
server_1  | {"level":"debug","msg":"Trusting 1 certs","time":"2017-02-14T08:33:30Z"}
server_1  | {"level":"info","msg":"Using remote signing service","time":"2017-02-14T08:33:30Z"}
server_1  | {"level":"info","msg":"Using mysql backend","time":"2017-02-14T08:33:30Z"}
server_1  | {"level":"info","msg":"Starting Server","time":"2017-02-14T08:33:30Z"}
server_1  | {"level":"info","msg":"Enabling TLS","time":"2017-02-14T08:33:30Z"}
server_1  | {"level":"info","msg":"Starting on :4443","time":"2017-02-14T08:33:30Z"}
server_1  | 2017/02/14 08:33:37 http: panic serving 10.166.17.43:57117: runtime error: invalid memory address or nil pointer dereference
server_1  | goroutine 92 [running]:
server_1  | net/http.(*conn).serve.func1(0xc4201a1400)
server_1  |     /usr/local/go/src/net/http/server.go:1491 +0x12a
server_1  | panic(0xa4c600, 0xc420012060)
server_1  |     /usr/local/go/src/runtime/panic.go:458 +0x243
server_1  | github.com/docker/notary/vendor/github.com/docker/distribution/context.getLogrusLogger(0x0, 0x0, 0xc4201a9998, 0x3, 0x3, 0x0)
server_1  |     /go/src/github.com/docker/notary/vendor/github.com/docker/distribution/context/logger.go:86 +0x5d
server_1  | github.com/docker/notary/vendor/github.com/docker/distribution/context.GetResponseLogger(0x0, 0x0, 0x8, 0xc42005e000)
server_1  |     /go/src/github.com/docker/notary/vendor/github.com/docker/distribution/context/http.go:176 +0x187
server_1  | github.com/docker/notary/utils.(*rootHandler).ServeHTTP.func1(0xc4201a9b30)
server_1  |     /go/src/github.com/docker/notary/utils/http.go:61 +0x3b
server_1  | github.com/docker/notary/utils.(*rootHandler).ServeHTTP(0xc420225180, 0xe16720, 0xc420143930, 0xc4200df4a0)
server_1  |     /go/src/github.com/docker/notary/utils/http.go:69 +0x7c4
server_1  | github.com/docker/notary/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202250e0, 0xe16720, 0xc420143930, 0xc4200df4a0)
server_1  |     /go/src/github.com/docker/notary/vendor/github.com/gorilla/mux/mux.go:98 +0x255
server_1  | net/http.serverHandler.ServeHTTP(0xc4201af000, 0xe16720, 0xc420143930, 0xc4200df4a0)
server_1  |     /usr/local/go/src/net/http/server.go:2202 +0x7d
server_1  | net/http.(*conn).serve(0xc4201a1400, 0xe17560, 0xc42025d540)
server_1  |     /usr/local/go/src/net/http/server.go:1579 +0x4b7
server_1  | created by net/http.(*Server).Serve
server_1  |     /usr/local/go/src/net/http/server.go:2293 +0x44d
```
I don't get much information from this output, seems the error is thrown when initializing the logger.
Checked the log of my token service, the endpoint didn't receive any request.

Any idea for further debug???
I appreciate your help.

### PR DESCRIPTION
**Pull request by reasonerjt**
A quick fix for the "nil reference" error, more details in #1097 

Signed-off-by: Tan Jiang <jiangd@vmware.com>

### CODE REVIEW

**Comment by riyazdf** [comment]
jenkins, test this please.

**Comment by ecordell** [comment]
LGTM as well, no preference on the approach really.

**Comment by riyazdf** [comment]
Yubikey tests are green:

```
	go test -tags pkcs11 -race -covermode atomic -coverprofile cmd/notary/coverage.pkcs11.txt -coverpkg github.com/docker/notary/storage,github.com/docker/notary,github.com/docker/notary/version,github.com/docker/notary/trustmanager/yubikey,github.com/docker/notary/cryptoservice,github.com/docker/notary/tuf/utils,github.com/docker/notary/server/snapshot,github.com/docker/notary/tuf,github.com/docker/notary/server/storage,github.com/docker/notary/tuf/data,github.com/docker/notary/server,github.com/docker/notary/client,github.com/docker/notary/trustmanager,github.com/docker/notary/passphrase,github.com/docker/notary/utils,github.com/docker/notary/tuf/signed,github.com/docker/notary/trustpinning,github.com/docker/notary/client/changelist,github.com/docker/notary/server/handlers,github.com/docker/notary/server/timestamp,github.com/docker/notary/tuf/validation,github.com/docker/notary/server/errors,github.com/docker/notary/cmd/notary,github.com/docker/notary/storage/rethinkdb github.com/docker/notary/cmd/notary
	go test -tags pkcs11 -race -covermode atomic -coverprofile trustmanager/yubikey/coverage.pkcs11.txt -coverpkg github.com/docker/notary/storage,github.com/docker/notary,github.com/docker/notary/trustmanager,github.com/docker/notary/passphrase,github.com/docker/notary/tuf/signed,github.com/docker/notary/tuf/utils,github.com/docker/notary/trustmanager/yubikey,github.com/docker/notary/tuf/validation,github.com/docker/notary/tuf/data github.com/docker/notary/trustmanager/yubikey

Results:

ok  	github.com/docker/notary/cmd/notary	129.302s	coverage: 63.3% of statements in <24 dependencies>
ok  	github.com/docker/notary/trustmanager/yubikey	18.689s	coverage: 23.6% of statements in <9 dependencies>
```

**Comment by endophage** [comment]
I'd really like to work out how we can ensure ctx is never nil. This feels like a sub-optimal patch for the immediate problem.

**Comment by riyazdf** [comment]
@endophage my hunch is that it's from an error'ed call to [root.auth.Authorized(...)](https://github.com/docker/notary/blob/c0cada48543847cf4a5cb4032aa121238d2109a1/utils/http.go#L106), which is vendored - @reasonerjt do you have any more light on the issue and the custom auth you implemented that might help?

**Comment by endophage** [comment]
@riyazdf that makes sense. We should do our best to log the "response completed" so maybe the auth call should assign its context return to a temporary variable and only replace the existing `ctx` if there are no errors?

**Comment by reasonerjt** [comment]
@riyazdf I don't think it has something to do with the custom auth.

making sure [doAuth(...)](https://github.com/docker/notary/blob/master/utils/http.go#L95) do not return nil context can also fix the problem.
either approach is OK to me as long as the nil reference error is gone.

**Comment by endophage** [comment]
@reasonerjt the auth code comes from another docker repo, and we've been discussing with @ecordell the possibility of making it more pluggable, so I wouldn't want to guarantee it will always return a non-nil context.

**Comment by HuKeping** [comment]
>  We should do our best to log the "response completed"

+1

**Comment by reasonerjt** [comment]
@HuKeping 

Considering all comments including this
https://github.com/docker/notary/pull/1081/files#diff-aa3046143cd12bfccc02a859a56d1036R64

I don't see a good solution, to ensure the message is logged with correct ctx, so will use this change in my env as workaround.

**Comment by HuKeping** [comment]
hmmm, it seems we should always check for the `nil`  whether the `doAuth` get errors or not. But it should  just be a sanity check,  it is the auth code's responsibility to return a non-nil ctx.

**Comment by cyli** [comment]
Last push was just to re-trigger all the tests.

**Comment by reasonerjt** [comment]
Hi, seems it's blocked at "test with yubikey hardware " ?

**Comment by riyazdf** [comment]
@reasonerjt can you please rebase this against the master branch?  I think you're picking up changes from another PR.

I can kickoff the yubikey tests

**Comment by riyazdf** [comment]
jenkins, test this please

**Comment by reasonerjt** [comment]
@riyazdf 

I've rebased, you may want to kick off another yubikey test.

**Comment by riyazdf** [comment]
jenkins, test this please

**Comment by riyazdf** [comment]
@endophage @HuKeping would you prefer that we defer this function call with the original context as the argument, even though it may be modified upon successful calls?  ex:

 ```
defer func(ctx context) {
       ctxu.GetResponseLogger(ctx).Info("response completed")
}(ctx)
```

**Comment by roman-vynar** [comment]
Any blockers on this?
Currently, the auth does not work with notary-server and crashes it.

**Comment by endophage** [comment]
@riyazdf I like that solution.

**Comment by reasonerjt** [comment]
If it's updated to:
```
defer func(ctx context) {
      ctxu.GetResponseLogger(ctx).Info("response completed")
}(ctx)
```
Will the PR be merged sooner?
Let's have it fixed as it blocks the scenario when "auth" is set in notary-server.

**Comment by endophage** [comment]
If you make that update today we'll merge before EOW.

**Comment by reasonerjt** [comment]
@endophage 
I've made the change as you suggested.

**Comment by endophage** [comment]
jenkins, test this please

**Comment by cyli** [comment]
LGTM - I've re-kicked the jenkins tests, there is a jenkins worker connection issue which is intermittently causing it to fail.

**Pull request merged**
