### PR TITLE
Fix gocyclo warning

### PR DESCRIPTION
**Pull request by HuKeping**
Part of #815 

Signed-off-by: Hu Keping <hukeping@huawei.com>

### CODE REVIEW

**Comment by cyli** [comment]
jenkins, test this please

**Comment by riyazdf** [comment]
thanks for the cleanup, LGTM!

**Comment by cyli** [comment]
jenkins, test this please

**Comment by cyli** [comment]
LGTM pending CI - thanks @HuKeping!

**Comment by HuKeping** [comment]
ping :)

**Comment by riyazdf** [comment]
thank you @HuKeping!

**Pull request merged**
