### PR TITLE
Don't compute an unnecessary cryptographic hash

### PR DESCRIPTION
**Pull request by mtrmac**
Signed-off-by: Miloslav Trmač <mitr@redhat.com>

### CODE REVIEW

**Comment by mtrmac** [comment]
See also https://github.com/endophage/gotuf/pull/51 .

**Comment by diogomonica** [comment]
Do we care? The size of a metadata file is always small, but I'll leave this to @endophage

**Comment by endophage** [comment]
There's no reason not to make this improvement.

LGTM.

@cyli @diogomonica can one of you take a look and LGTM/comment. It's super short.

**Comment by cyli** [comment]
LGTM

**Comment by endophage** [comment]
@mtrmac When I moved gotuf into this repo I added a contributors file (mainly because gotuf had one). Feel free to submit a PR to add yourself to that file. It's not in any particular order.

**Pull request merged**
