### PR TITLE
Ensure that SetMeta creates parent directory first

### LINKED ISSUE #355: Maybe TUF metadata filestore should ensure the directories of the file
E.g. it automatically creates all the parent directories it needs.

See https://github.com/docker/notary/pull/335#discussion_r47295933.

### PR DESCRIPTION
**Pull request by diogomonica**
Fixes #355

@cyli 

Signed-off-by: Diogo Monica <diogo@docker.com>

### CODE REVIEW

**Comment by endophage** [comment]
This may become necessary with delegations so we should make sure it's in.

LGTM.

**Comment by riyazdf** [comment]
LGTM!

**Comment by cyli** [comment]
LGTM thanks for fixing so fast!  :D

**Comment by diogomonica** [comment]
@cyli you're amazing at actionable, descriptive issues. It's a pleasure closing those down ;)

**Pull request merged**
